### ISSUE TITLE
Add custom fortunes

### ISSUE THREAD

**Issue by jasonmacduffie** [316k/android-fortune#2]
I want to view fortunes I have saved on my device.

**Comment by 316k** [comment]
I'll see what I can do, but I'm pretty busy right now.

`fortune` is a pretty simple software idea, but Android's concepts and limitations make it difficult to keep it as simple as it was in the good old Unix days. This would require to double (or even triple) the project's code.

Anyway, thanks for the interest in this app ! Feel free to make me a pull-request if you know how to do this.

**Comment by ildar** [comment]
That's weird. You read fortunes from the assets. Isn't it trivial just read them from a file on SD card?
You don't even need to add new permissions if you use /sdcard/Android/data/$APP.

**Comment by 316k** [comment]
You're right... The first thing I looked for was a menu to import a file from the app (and that looked a bit painful), but I'll add something that reads from the files from /sdcard/Android/data/$APP
Not sure why this solution didn't pop earlier in my mind...

I'm still as busy as I was on October 1st 2015, so I'll have to take some time and just do it anyway.

Thanks for the comment !

**Comment by 316k** [comment]
Files in `sdcard/fortunes` are now read, along with the system fortunes.
If I didn't mess up my release, F-Droid should update to the the version 2.0 soon !
